# Generated by Django 5.0.6 on 2024-06-14 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 14, 12, 34, 26, 161834)),
            preserve_default=False,
        ),
    ]
